serverInfo:
  name: "AcesListenerArk"
  description: "ACES Listener implementation for Ark"
  version: "1.1.0"
  websiteUrl: "https://arkaces.com"

# The default application database is an in memory database. Uncomment the lines 10-16 below to use a
# local file database instead:
#spring:
#  datasource:
#    url: "jdbc:h2:/tmp/ark-encoded-listener.db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
#    driver-class-name: "org.h2.Driver"
#  jpa:
#    hibernate:
#      ddl-auto: "create-drop"

# Ark network config YML that listening will be performed against
arkNetworkConfigPath: "ark_network_config/mainnet.yml"

# Number of Transactions to scan through each execution cycle
scanTransactionDepth: 500

server:
  port: 9091

arkAuth:
  requireAuth: false

# The following restricts logging to errors. Comment out lines 31-33 below to get more verbose logging
logging:
  level:
    com.arkaces.aces_listener_ark.ArkEventListener: ERROR
