server:
  # Port the application runs on
  port: 9091

serverInfo:
  name: "AcesListenerArk"
  description: "ACES Listener implementation for Ark"
  version: "1.1.0"
  websiteUrl: "https://arkaces.com"

spring:
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/aces_listener_ark_db"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "validate"

flyway:
  enabled: true

# Ark network config YML that listening will be performed against
arkNetworkConfigPath: "ark_network_config/mainnet.yml"

# Number of Transactions to scan through each execution cycle
scanTransactionDepth: 500

# Number of seconds between transaction scans
scanIntervalSec: 5

# Enable event log controller troubleshooting event webhook callbacks, see: EventLogController
enableEventLogController: "false"

# The following restricts logging to errors. Comment out lines below to get more verbose logging
logging:
  level:
    com.arkaces.aces_listener_ark.ArkEventListener: ERROR
